### ISSUE TITLE
[Feature Request] Scan from already taken image.

### ISSUE THREAD

**Issue by tejas-bhong** [G00fY2/quickie#198] opened 2024-09-19 16:12 UTC
There should be solution to get the scan result from an image which is already taken like from gallery, etc.

**Comment by tejas-bhong** [comment] 2024-09-19 16:19
I saw there is a closed issue for this same feature request to which you closed saying:

> The focus of quickie is about an easy integration with the camera and therefore UI focused. Calling native filepicker and sending the file uri to the scanner would require this library to decouple the barcode scanner from CameraX (which is currently not the case).

But, what I want is just a way for the app to pass the image as ByteArray or URI or whatever you find easy, which the library will scan and give the scan result back.

**Comment by G00fY2** [comment] 2024-09-19 17:10
Hi and thanks for this FR. As you already notices this is a duplicate of #32. The library is build around CameraX for setting up the camera and allowing live QR code scanning (thats what most of the code is about). Processing the image is basically just a one liner:
https://github.com/G00fY2/quickie/blob/a971f09a0e2feb5a4b0e8f15622a4d0d3989f9bf/quickie/src/main/kotlin/io/github/g00fy2/quickie/QRCodeAnalyzer.kt#L48

If you just need this functionality I encourage you to integrate ML Kit manually.

**Closed by G00fY2** 2024-09-19 17:10 UTC
